Completed HW 23.1 and 24.1
RomanMinevich/shop pull request #5
Opened 2019-10-06 15:23 UTC by RomanMinevich

2019-10-06 18:50 UTC, boroda4436 requested changes

2019-10-06 18:50 UTC, boroda4436 commented on src/main/java/mate.academy.internetshop/controller/BucketController.java
> +        request.setAttribute("items", bucketService.get(userId).getItems());
@RomanMinevich Це не корректно передавати userId в метод get. Очікується що сюди потрібно передавати bucketId. Попередня версія з getByUserId більш корректно буде виглялдати

2019-10-06 18:50 UTC, boroda4436 commented on src/main/java/mate.academy.internetshop/dao/RoleDao.java
> +    Set<Role> getUserRoles(Long userId);
@RomanMinevich Думаю що цей метод було б краще використати в userDao, а ще краще витягувати ролі прямо з user'a

2019-10-06 18:50 UTC, boroda4436 commented on src/main/java/mate.academy.internetshop/dao/UserDao.java
> +    User getByToken(String token);
@RomanMinevich А чому прибрав Optional?

2019-10-07 11:58 UTC, RomanMinevich commented on src/main/java/mate.academy.internetshop/controller/BucketController.java
> +        request.setAttribute("items", bucketService.get(userId).getItems());
Виправив

2019-10-07 12:03 UTC, RomanMinevich commented on src/main/java/mate.academy.internetshop/dao/RoleDao.java
> +    Set<Role> getUserRoles(Long userId);
Переніс даний метод до UserDao і додав змінну Set<Role> roles до User (отримати перелік ролей користувача тепер можна "прямо з user'a")

2019-10-07 12:08 UTC, RomanMinevich commented on src/main/java/mate.academy.internetshop/dao/UserDao.java
> +    User getByToken(String token);
За непотрібнісію) 
![Снимок экрана 2019-10-07 в 15 05 07](https://user-images.githubusercontent.com/52323566/66310197-3fc4f180-e914-11e9-8761-9fdf2f7f3d0d.png)
![Снимок экрана 2019-10-07 в 15 06 17](https://user-images.githubusercontent.com/52323566/66310198-3fc4f180-e914-11e9-995f-b01b9e6e3acc.png)

2019-10-07 12:37 UTC, boroda4436 approved these changes

2019-10-07 13:29 UTC, merged